#![feature(nonpoison_mutex)]
#![feature(sync_nonpoison)]

use std::{path::PathBuf, sync::Arc, time::Duration};

use clap::Parser;
use tokio::sync::Mutex;
use tokio_util::sync::CancellationToken;
use tracing::info;

mod control;
mod gpio;
mod hdmi;
mod overlay;
mod smartplug;
mod tv;

use hdmi::HdmiReady;
use tv::TvPower;

// ---------------------------------------------------------------------------
// CLI — only used to locate the config file
// ---------------------------------------------------------------------------

#[derive(clap::Parser, Debug)]
struct Cli {
    /// Path to the TOML configuration file
    #[clap(long, default_value = "/srv/babooshka-config.toml")]
    config: PathBuf,
}

// ---------------------------------------------------------------------------
// Configuration (loaded from TOML)
// ---------------------------------------------------------------------------

#[derive(Debug, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct Config {
    /// File to save/restore playback state
    #[serde(default = "defaults::play_state")]
    play_state: PathBuf,

    /// JSON playlist file
    #[serde(default = "defaults::playlist")]
    playlist: PathBuf,

    #[serde(default)]
    gpio: GpioConfig,

    #[serde(default)]
    tv: TvConfig,

    #[serde(default)]
    hdmi: HdmiConfig,

    /// Path to the Unix socket for software switch overrides.
    /// Send `on\n` or `off\n` to simulate the switch changing state.
    /// Set to an empty string to disable.
    #[serde(default = "defaults::control_socket")]
    control_socket: PathBuf,

    /// Optional path to a JSON file mapping video paths to gain adjustments in dB.
    /// Generated by `playlistctl`.  Set to an empty string to disable.
    #[serde(default = "defaults::gain_db")]
    gain_db: PathBuf,

    /// Whether to actually apply the gains from `gain_db`.
    ///
    /// The map is loaded and logged either way, so a run can be checked against
    /// real playback before the gains take effect.  Off by default: applying an
    /// untrusted gain map would change the volume of every film at once.
    #[serde(default)]
    gain_enabled: bool,
}

#[derive(Debug, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct GpioConfig {
    /// BCM pin number for the switch input (pull-up; to-ground = inactive)
    #[serde(default = "defaults::gpio_switch_pin")]
    switch_pin: u8,

    /// BCM pin number for the status LED output
    #[serde(default = "defaults::gpio_led_pin")]
    led_pin: u8,
}

impl Default for GpioConfig {
    fn default() -> Self {
        Self {
            switch_pin: defaults::gpio_switch_pin(),
            led_pin: defaults::gpio_led_pin(),
        }
    }
}

#[derive(Debug, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct TvConfig {
    /// "smartplug", "cec", or "both"
    #[serde(default = "defaults::tv_control")]
    control: TvControlMode,

    /// Home Assistant base URL
    #[serde(default = "defaults::ha_url")]
    ha_url: String,

    /// Home Assistant long-lived access token
    ha_token: Option<String>,

    /// Home Assistant entity ID for the smart plug
    #[serde(default = "defaults::ha_entity")]
    ha_entity: String,
}

impl Default for TvConfig {
    fn default() -> Self {
        Self {
            control: defaults::tv_control(),
            ha_url: defaults::ha_url(),
            ha_token: None,
            ha_entity: defaults::ha_entity(),
        }
    }
}

#[derive(Debug, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct HdmiConfig {
    /// "drm", "timeout", or "cec"
    #[serde(default = "defaults::hdmi_detect")]
    detect: HdmiDetectMode,

    /// Seconds to wait when using the "timeout" detection mode,
    /// or the fallback timeout for "cec" mode
    #[serde(default = "defaults::hdmi_timeout_secs")]
    timeout_secs: u64,

    /// Path to the DRM connector status sysfs file (used in "drm" mode)
    #[serde(default = "defaults::hdmi_drm_path")]
    drm_path: PathBuf,

    /// Path to the CEC device (used in "cec" mode)
    #[serde(default = "defaults::cec_device")]
    cec_device: PathBuf,
}

impl Default for HdmiConfig {
    fn default() -> Self {
        Self {
            detect: defaults::hdmi_detect(),
            timeout_secs: defaults::hdmi_timeout_secs(),
            drm_path: defaults::hdmi_drm_path(),
            cec_device: defaults::cec_device(),
        }
    }
}

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
enum TvControlMode {
    Smartplug,
    Cec,
    Both,
    /// Does not touch the TV at all; shows a swaynag notification instead.
    DryRun,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
enum HdmiDetectMode {
    Drm,
    Timeout,
    Cec,
}

mod defaults {
    use super::{HdmiDetectMode, TvControlMode};
    use std::path::PathBuf;

    pub fn play_state() -> PathBuf {
        "/srv/play-state.json".into()
    }
    pub fn playlist() -> PathBuf {
        "/srv/playlist.json".into()
    }
    pub fn gpio_switch_pin() -> u8 {
        17
    }
    pub fn gpio_led_pin() -> u8 {
        27
    }
    pub fn tv_control() -> TvControlMode {
        TvControlMode::Smartplug
    }
    pub fn ha_url() -> String {
        "http://10.22.0.50:8123".into()
    }
    pub fn ha_entity() -> String {
        "switch.bare_tv_switch".into()
    }
    pub fn hdmi_detect() -> HdmiDetectMode {
        HdmiDetectMode::Drm
    }
    pub fn hdmi_timeout_secs() -> u64 {
        15
    }
    pub fn hdmi_drm_path() -> PathBuf {
        "/sys/class/drm/card1-HDMI-A-1/status".into()
    }
    pub fn cec_device() -> PathBuf {
        "/dev/cec0".into()
    }
    pub fn control_socket() -> PathBuf {
        "/tmp/run/babooshka-control.sock".into()
    }
    pub fn gain_db() -> PathBuf {
        "".into()
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .with_level(true)
        .init();

    let cli = Cli::parse();

    let config_text = std::fs::read_to_string(&cli.config)
        .unwrap_or_else(|e| panic!("Failed to read config file {}: {e}", cli.config.display()));
    let config: Config = toml::from_str(&config_text)
        .unwrap_or_else(|e| panic!("Failed to parse config file {}: {e}", cli.config.display()));

    tracing::info!("Loaded config from {}: {config:#?}", cli.config.display());

    // Build TV power controller
    let tv: Box<dyn TvPower> = match config.tv.control {
        TvControlMode::Smartplug => {
            let token = config
                .tv
                .ha_token
                .clone()
                .expect("tv.ha_token is required in config for smartplug mode");
            Box::new(smartplug::SmartPlug {
                base_url: config.tv.ha_url.clone(),
                entity_id: config.tv.ha_entity.clone(),
                token,
            })
        }
        TvControlMode::Cec => Box::new(tv::CecTv),
        TvControlMode::DryRun => Box::new(tv::DryRunTv),
        TvControlMode::Both => {
            let token = config
                .tv
                .ha_token
                .clone()
                .expect("tv.ha_token is required in config for 'both' mode");
            Box::new(tv::CombinedTv {
                primary: Box::new(smartplug::SmartPlug {
                    base_url: config.tv.ha_url.clone(),
                    entity_id: config.tv.ha_entity.clone(),
                    token,
                }),
                fallback: Box::new(tv::CecTv),
            })
        }
    };

    // Build HDMI ready detector
    let hdmi_ready: Box<dyn HdmiReady> = match config.hdmi.detect {
        HdmiDetectMode::Drm => Box::new(hdmi::DrmPoll {
            path: config.hdmi.drm_path.clone(),
            poll_interval: Duration::from_millis(500),
        }),
        HdmiDetectMode::Timeout => Box::new(hdmi::FixedTimeout {
            duration: Duration::from_secs(config.hdmi.timeout_secs),
        }),
        HdmiDetectMode::Cec => Box::new(hdmi::CecReady {
            device: config.hdmi.cec_device.clone(),
            timeout: Duration::from_secs(config.hdmi.timeout_secs),
        }),
    };

    // Set up GPIO switch
    let (_switch_pin, switch_tx, mut switch_rx) =
        gpio::setup_switch(config.gpio.switch_pin).expect("failed to configure GPIO switch pin");

    // Notify for "skip to next file" commands from the control socket.
    let skip_notify = Arc::new(tokio::sync::Notify::new());
    // Notify for "rewind current file to start" commands from the control socket.
    let rewind_notify = Arc::new(tokio::sync::Notify::new());

    // Spawn software control socket (shares the same sender as the GPIO interrupt).
    if !config.control_socket.as_os_str().is_empty() {
        control::spawn(config.control_socket.clone(), switch_tx, skip_notify.clone(), rewind_notify.clone());
    }

    // Load optional gain map (path → dB).  Empty path = disabled.
    let loaded_gain_map: std::collections::HashMap<String, f64> =
        if config.gain_db.as_os_str().is_empty() {
            std::collections::HashMap::new()
        } else {
            match std::fs::read_to_string(&config.gain_db) {
                Ok(s) => serde_json::from_str(&s).unwrap_or_else(|e| {
                    tracing::warn!("Failed to parse gain_db file: {e}");
                    std::collections::HashMap::new()
                }),
                Err(e) => {
                    tracing::warn!("Could not read gain_db file {}: {e}", config.gain_db.display());
                    std::collections::HashMap::new()
                }
            }
        };

    // Report the map regardless, so a dry run shows exactly what would change,
    // then hand the state machine an empty map unless gains are switched on.
    let gain_map = if config.gain_enabled {
        info!("Volume normalisation ON — {} file(s) have a gain", loaded_gain_map.len());
        loaded_gain_map
    } else {
        for (path, gain) in &loaded_gain_map {
            info!("Volume normalisation OFF — would apply {gain:+.1} dB to {path}");
        }
        info!(
            "Volume normalisation OFF ({} file(s) available); set gain_enabled = true to apply",
            loaded_gain_map.len()
        );
        std::collections::HashMap::new()
    };

    let mut overlay = overlay::Overlay::new();
    run_state_machine(config, tv, hdmi_ready, &mut switch_rx, skip_notify, rewind_notify, gain_map, &mut overlay).await;
}

// ---------------------------------------------------------------------------
// State machine
// ---------------------------------------------------------------------------

async fn run_state_machine(
    config: Config,
    tv: Box<dyn TvPower>,
    hdmi_ready: Box<dyn HdmiReady>,
    switch_rx: &mut tokio::sync::watch::Receiver<bool>,
    skip_notify: Arc<tokio::sync::Notify>,
    rewind_notify: Arc<tokio::sync::Notify>,
    gain_map: std::collections::HashMap<String, f64>,
    overlay: &mut overlay::Overlay,
) {
    loop {
        // ---- IDLE: wait for switch to go active (HIGH) ----
        info!("State: IDLE — waiting for switch");
        if let Err(e) = gpio::set_led(config.gpio.led_pin, false) {
            tracing::warn!("Failed to set LED off: {e}");
        }
        overlay
            .show("babooshka | IDLE — switch=LOW, waiting for activation")
            .await;
        // Check current state first — don't wait for a transition if already active.
        loop {
            if *switch_rx.borrow_and_update() {
                break;
            }
            switch_rx.changed().await.ok();
        }

        info!("Switch activated — entering BOOTING state");

        // ---- BOOTING: turn on TV, blink LED, wait for HDMI ----
        overlay
            .show(&format!(
                "babooshka | BOOTING — switch=HIGH, tv={:?}, hdmi=waiting",
                config.tv.control
            ))
            .await;
        if let Err(e) = tv.turn_on().await {
            tracing::error!("Failed to turn on TV: {e}");
        }

        let blink_cancel = CancellationToken::new();
        {
            let cancel = blink_cancel.clone();
            let led_pin = config.gpio.led_pin;
            tokio::spawn(async move {
                if let Err(e) =
                    gpio::blink_led(led_pin, Duration::from_millis(500), cancel, true).await
                {
                    tracing::warn!("LED blink task error: {e}");
                }
            });
        }

        // Ignore switch transitions during BOOTING — grandma may flip the switch
        // multiple times while the TV is powering on.  We only abort if the switch
        // is still LOW once HDMI is ready (checked in the grace period below).
        hdmi_ready.wait_until_ready().await;
        info!("HDMI ready — starting playback");

        blink_cancel.cancel();

        // ---- PLAYING ----
        info!("State: PLAYING");
        // Hide the overlay while mpv is on screen — it would cover the video.
        overlay.hide().await;

        let playlist = player::playlist::Playlist::load_from_file(&config.playlist)
            .await
            .expect("failed to read playlist");

        let first_file = playlist.items[0].clone();
        let mut mpv_player = player::api::MpvPlayer::new(&first_file.to_string_lossy())
            .await
            .expect("failed to start mpv");

        let watch_later = player::watch_later::load_from_file(&config.play_state)
            .await
            .unwrap();
        let initial_file = if let Some(ref state) = watch_later {
            mpv_player.restore_state(state).await.unwrap();
            state.path.to_string_lossy().into_owned()
        } else {
            first_file.to_string_lossy().into_owned()
        };
        if let Some(&gain) = gain_map.get(&initial_file) {
            info!("Applying gain {gain:+.1} dB for {initial_file}");
            mpv_player.set_volume_gain(gain).await.unwrap_or_else(|e| {
                tracing::warn!("Failed to set volume gain: {e}");
            });
        }

        let mpv = Arc::new(Mutex::new(mpv_player));

        // Spawn state-save task
        let save_handle = {
            let mpv = mpv.clone();
            let play_state = config.play_state.clone();
            tokio::spawn(async move {
                let mut last_state = watch_later;
                loop {
                    tokio::time::sleep(Duration::from_millis(1000)).await;
                    let state = match mpv.lock().await.save_state().await {
                        Ok(s) => s,
                        Err(e) => {
                            tracing::warn!("Failed to save playback state: {e}");
                            continue;
                        }
                    };
                    let new_state = Some(state);
                    if last_state != new_state {
                        if let Err(e) = tokio::fs::write(
                            &play_state,
                            serde_json::to_string(&new_state).unwrap(),
                        )
                        .await
                        {
                            tracing::warn!("Failed to write play state: {e}");
                        }
                        last_state = new_state;
                    }
                }
            })
        };

        // Spawn playlist-advance task (also handles skip/rewind commands)
        let advance_handle = {
            let mpv = mpv.clone();
            let skip_notify = skip_notify.clone();
            let rewind_notify = rewind_notify.clone();
            let gain_map = gain_map.clone();
            tokio::spawn(async move {
                loop {
                    // Wait up to 5 s, but yield immediately if a skip or rewind arrives.
                    enum Action { Timer, Skip, Rewind }
                    let action = tokio::select! {
                        _ = tokio::time::sleep(Duration::from_millis(5000)) => Action::Timer,
                        _ = skip_notify.notified() => Action::Skip,
                        _ = rewind_notify.notified() => Action::Rewind,
                    };

                    if matches!(action, Action::Rewind) {
                        info!("Rewind requested — seeking to start of current file");
                        mpv.lock().await.set_playback_time(0.0).await.unwrap_or_else(|e| {
                            tracing::warn!("Failed to seek to start: {e}");
                        });
                        continue;
                    }

                    let should_advance = if matches!(action, Action::Skip) {
                        info!("Skip requested — advancing to next file");
                        true
                    } else {
                        let duration = match mpv.lock().await.get_file_duration().await {
                            Ok(d) => d,
                            Err(e) => {
                                tracing::warn!("Could not get file duration: {e}");
                                continue;
                            }
                        };
                        let position = match mpv.lock().await.get_playback_time().await {
                            Ok(p) => p,
                            Err(e) => {
                                tracing::warn!("Could not get playback time: {e}");
                                continue;
                            }
                        };
                        info!("duration: {duration:.1}, position: {position:.1}");
                        (duration - position).abs() < 5.0
                    };

                    if should_advance {
                        let current_file = mpv.lock().await.get_path().await.unwrap();
                        let next_file = playlist.next_file(&current_file.into());
                        info!("Advancing to next file: {}", next_file.display());
                        let next_str = next_file.to_string_lossy().into_owned();
                        mpv.lock().await.loadfile(&next_str).await.unwrap();
                        if let Some(&gain) = gain_map.get(&next_str) {
                            info!("Applying gain {gain:+.1} dB for {next_str}");
                            mpv.lock().await.set_volume_gain(gain).await.unwrap_or_else(|e| {
                                tracing::warn!("Failed to set volume gain: {e}");
                            });
                        } else {
                            // Reset to 0 dB so a previous file's gain doesn't carry over.
                            mpv.lock().await.set_volume_gain(0.0).await.unwrap_or(());
                        }
                    }
                }
            })
        };

        // Spawn mpv health-check task — returns when mpv dies
        let health_handle = {
            let mpv = mpv.clone();
            tokio::spawn(async move {
                loop {
                    tokio::time::sleep(Duration::from_millis(2125)).await;
                    if !mpv.lock().await.is_running() {
                        tracing::warn!("mpv process exited");
                        return;
                    }
                }
            })
        };
        let health_abort = health_handle.abort_handle();

        // Grace period: ignore switch state for 5 s after entering PLAYING so that
        // any bounces during the boot sequence don't immediately trigger a shutdown.
        // After the grace period, check the switch — if it's already LOW, shut down.
        tokio::time::sleep(Duration::from_secs(5)).await;
        switch_rx.borrow_and_update(); // discard any transitions that occurred during grace
        if !*switch_rx.borrow() {
            info!("Switch is LOW after grace period — shutting down");
            save_handle.abort();
            advance_handle.abort();
            health_abort.abort();
        } else {
        // Wait: switch goes low, mpv dies, or Ctrl-C
        tokio::select! {
            _ = wait_for_switch_low(switch_rx) => {
                info!("Switch deactivated — shutting down player");
            }
            _ = health_handle => {
                tracing::warn!("mpv died unexpectedly");
            }
            _ = tokio::signal::ctrl_c() => {
                info!("Received Ctrl-C");
                save_handle.abort();
                advance_handle.abort();
                health_abort.abort();
                if let Ok(state) = mpv.lock().await.save_state().await {
                    let _ = tokio::fs::write(
                        &config.play_state,
                        serde_json::to_string(&Some(state)).unwrap(),
                    )
                    .await;
                }
                let _ = mpv.lock().await.send_quit().await;
                if let Err(e) = tv.turn_off().await {
                    tracing::error!("Failed to turn off TV: {e}");
                }
                if let Err(e) = gpio::set_led(config.gpio.led_pin, false) {
                    tracing::warn!("Failed to set LED off: {e}");
                }
                overlay.hide().await;
                return;
            }
        }

        save_handle.abort();
        advance_handle.abort();
        health_abort.abort();
        } // end of grace-period else block

        // ---- SHUTTING DOWN ----
        info!("State: SHUTTING DOWN");
        overlay
            .show("babooshka | SHUTTING DOWN — switch=LOW, saving state, stopping mpv")
            .await;

        if let Ok(state) = mpv.lock().await.save_state().await {
            let _ = tokio::fs::write(
                &config.play_state,
                serde_json::to_string(&Some(state)).unwrap(),
            )
            .await;
        }

        if let Err(e) = mpv.lock().await.send_quit().await {
            tracing::warn!("Failed to send quit to mpv: {e}");
        }

        if let Err(e) = tv.turn_off().await {
            tracing::error!("Failed to turn off TV: {e}");
        }

        if let Err(e) = gpio::set_led(config.gpio.led_pin, false) {
            tracing::warn!("Failed to set LED off: {e}");
        }

        info!("Shutdown complete — returning to IDLE");
    }
}

/// Wait until the switch transitions to inactive (LOW / false).
async fn wait_for_switch_low(switch_rx: &mut tokio::sync::watch::Receiver<bool>) {
    loop {
        switch_rx.changed().await.ok();
        if !*switch_rx.borrow() {
            return;
        }
    }
}
